server:
  port: 0
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: member
  config:
    import: "optional:configserver:http://localhost:7777/"
  cloud:
    config:
      name: info
      profile: default
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://54.180.157.223:3306/pickpack?
##    url: jdbc:mysql://localhost:3306/pickpack?
#    username: root
#    password: ssafy

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

