spring:
  application:
    name: item-service
  cloud:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pickpack?
      username: ssafy # MySQL DB Username
      password: ssafy # MySQL DB password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql : debug
