server:
  port: 0
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: item
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.157.223:3306/pickpack?
    username: root # MySQL DB Username
    password: ssafy # MySQL DB password
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql : debug
cloud:
  aws:
    credentials:
      access-key: # 승희에게 문의
      secret-key: #
    s3:
      bucket: pickpack8
    region:
      static: ap-northeast-2
    stack:
      auto: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"