spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8b307.p.ssafy.io:3306/pickpack?
    username: root # MySQL DB Username
    password:  # MySQL DB password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql : debug
