server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER
          predicates:
            - Path=/api/member/**

        - id: chat-service
          uri: lb://CHAT
          predicates:
            - Path=/api/chat/**

        - id: item-service
          uri: lb://ITEM
          predicates:
            - Path=/api/item/**

        - id: flight-service
          uri: lb://FLIGHT
          predicates:
            - Path=/api/flight/**

logging:
  config: classpath:Logback-spring.xml